/**:
  twist_mux:
    ros__parameters:
      use_stamped: true
      topics:
        navigation:
          topic   : nav_vel
          timeout : 0.5
          priority: 10
        keyboard:
          topic   : key_vel
          timeout : 0.5
          priority: 100
        joy:
          topic   : joy_vel
          timeout : 0.5
          priority: 110
        scenario:
          topic   : scenario_vel
          timeout : 0.5
          priority: 70
        safety:
          topic   : safety_vel
          timeout : 0.5
          priority: 90